# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at
  # https://dart-lang.github.io/linter/lints/index.html.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    require_trailing_commas: true
    use_super_parameters: true
    always_put_required_named_parameters_first: true
    always_declare_return_types: true
    avoid_print: true
    curly_braces_in_flow_control_structures: true
    sized_box_shrink_expand: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: false
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: false
    one_member_abstracts: false
    # only_throw_errors: true
    package_api_docs: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    camel_case_types: true
    library_names: true
    file_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    constant_identifier_names: false
    directives_ordering: true
    # slash_for_doc_comments: false
    # prefer_interpolation_to_compose_strings: true
    # prefer_collection_literals: true
    # avoid_function_literals_in_foreach_calls: false
    # avoid_init_to_null: true
    # prefer_initializing_formals: true
    # type_init_formals: true
    # empty_constructor_bodies: true
    # empty_statements: true
    # unnecessary_new: true
    # unnecessary_this: true
    # unnecessary_const: true
    # unnecessary_overrides: true
    # unnecessary_parenthesis: true
    # unnecessary_getters_setters: true
    # avoid_setters_without_getters: true
    # avoid_return_types_on_setters: true
    # parameter_assignments: true
    # prefer_function_declarations_over_variables: false
    # unawaited_futures: true
    # prefer_relative_imports: true
    # annotate_overrides: false
    # overridden_fields: false
    # deprecated_member_use: true


    # avoid_print: false  # Uncomment to disable the `avoid_print` rule
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
